version: "3"
services:
    nginx:
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app: 
        build: 
            context: . 
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            NODE_ENV: development
            MONGO_USER: tmash
            MONGO_PASSWORD: mypassword
            SESSION_SECRET: mysecret
        command: npm run dev

    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: tmash
            MONGO_INITDB_ROOT_PASSWORD: mypassword