secrets:
  mongo-pass:
    file: C:\Users\Titus\Desktop\Devops\mongo-pass.txt
  mongo-user:
    file: C:\Users\Titus\Desktop\Devops\mongo-user.txt
services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/mongo-pass
      MONGO_INITDB_ROOT_USERNAME: /run/secrets/mongo-user
    image: mongo
    secrets:
    - source: mongo-pass
    - source: mongo-user
    volumes:
    - mongo-db-storage:/data/db:rw
  nginx:
    depends_on:
      node-app:
        condition: service_started
    image: nginx:stable-alpine
    ports:
    - published: 3000
      target: 80
    - published: 80
      target: 80
    volumes:
    - C:\Users\Titus\Desktop\Devops\nginx\default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      args:
        NODE_ENV: production
      context: C:\Users\Titus\Desktop\Devops
    command: node index.js
    depends_on:
      mongodb:
        condition: service_started
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        delay: 15s
        failure_action: rollback
        parallelism: 2
    environment:
      MONGO_PASSWORD: mongo-pass
      MONGO_USER: mongo-user
      NODE_ENV: production
      PORT: '3000'
      SESSION_SECRET: mysecret
    image: tjmash/node-app
  redis:
    image: redis
version: '3.1'
volumes:
  mongo-db-storage: {}

